export const chats = [
  {
    id: 1,
    name: 'Игорь',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: '12:05',
    date: new Date().toISOString(),
    status: 'online',
  },
  {
    id: 2,
    name: 'Андрей',
    lastMessage: '???',
    shortDate: '11:00',
    date: new Date().toISOString(),
    status: 'online',
    authorIsUser: true,
  },
  {
    id: 3,
    name: 'Новости',
    lastMessage:
      'Маршрут Москва - Санкт-Петербург стал самым популярным внутрироссийским направлением среди авиапутешественников в ноябре',
    shortDate: '07:05',
    date: new Date().toISOString(),
    status: 'offline',
    unreadMessages: 2,
  },
  {
    id: 4,
    name: 'Егор',
    lastMessage: 'Привет, ты тут?',
    shortDate: 'Вчера',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 5,
    name: 'Владимир',
    lastMessage:
      'Маршрут Москва - Санкт-Петербург стал самым популярным внутрироссийским направлением среди авиапутешественников в ноябре',
    shortDate: 'Вчера',
    date: new Date().toISOString(),
    status: 'online',
    unreadMessages: 21,
  },
  {
    id: 6,
    name: 'Елена',
    lastMessage:
      'Первые беспилотные грузовики могут проехать по трассе М11 летом 2023 года',
    shortDate: 'Пн',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 7,
    name: 'София',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: 'Вт',
    date: new Date().toISOString(),
    status: 'offline',
    unreadMessages: 1,
  },
  {
    id: 8,
    name: 'Кирилл',
    lastMessage:
      'Синоптик предупредил москвичей о резком похолодании на следующей неделе',
    shortDate: '1 июня 2021',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 9,
    name: 'Денис',
    lastMessage:
      'Маршрут Москва - Санкт-Петербург стал самым популярным внутрироссийским направлением среди авиапутешественников в ноябре',
    shortDate: '2 мая 2021',
    date: new Date().toISOString(),
    status: 'online',
  },
  {
    id: 10,
    name: 'Новости',
    lastMessage:
      'Первые беспилотные грузовики могут проехать по трассе М11 летом 2023 года',
    shortDate: '28 апреля 2021',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 11,
    name: 'Игорь',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: '12:05',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 12,
    name: 'Андрей',
    lastMessage: '???',
    shortDate: '12 Июня 2021',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 13,
    name: 'Новости',
    lastMessage:
      'Маршрут Москва - Санкт-Петербург стал самым популярным внутрироссийским направлением среди авиапутешественников в ноябре',
    shortDate: '07:05',
    date: new Date().toISOString(),
    status: 'online',
    unreadMessages: 2,
  },
  {
    id: 14,
    name: 'Егор',
    lastMessage: 'Привет, ты тут?',
    shortDate: 'Вчера',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 15,
    name: 'Владимир',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: 'Вчера',
    date: new Date().toISOString(),
    status: 'online',
  },
  {
    id: 16,
    name: 'Игорь',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: '12:05',
    date: new Date().toISOString(),
    status: 'offline',
  },
  {
    id: 17,
    name: 'Андрей',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    shortDate: '12:05',
    date: new Date().toISOString(),
    status: 'offline',
  },
];
